//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class mAttachmentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mAttachmentType()
        {
            this.UserDocuments = new HashSet<UserDocument>();
        }
    
        public int AttachmentTypeID { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> AttachmentID { get; set; }
        public string TabName { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> RevisedBy { get; set; }
        public Nullable<System.DateTime> ReviesedOn { get; set; }
    
        public virtual mAttachment mAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDocument> UserDocuments { get; set; }
    }
}
