//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDocument
    {
        public int DocumentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string DocumentName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime UploadDate { get; set; }
        public Nullable<int> AttachmentTypeID { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> RevisedBy { get; set; }
        public Nullable<System.DateTime> ReviesedOn { get; set; }
    
        public virtual mAttachmentType mAttachmentType { get; set; }
    }
}
